import { EmergencyContact, BarangayInfo, HazardGuide, GoBagItem, AdvisoryItem } from '../types';

export const OFFICIAL_HOTLINES: EmergencyContact[] = [
  {
    id: 'cdrmmo-1',
    name: 'Iligan City Disaster Risk Reduction & Management Department (ICDRRMD)',
    agency: 'Iligan City Government / ICDRRMD',
    numbers: ['(063) 221-8459', '0997-726-2692', '0969-233-7878'],
    category: 'rescue',
    address: 'Seminary Drive, Pala-o, Iligan City',
    description: 'Official 24/7 Communication Center for Emergency Rescue, Flood & Landslide Evacuation, Disaster Monitoring, and Quick Response in Iligan City. Official FB: facebook.com/drrmoiligancity',
    isAvailable247: true,
  },
  {
    id: 'pnp-iligan',
    name: 'Iligan City Police Office (ICPO HQ & Police Stations)',
    agency: 'Philippine National Police (PNP)',
    numbers: ['(063) 221-6699', '167', '0917-700-1660', '(063) 222-2115', '166'],
    category: 'police',
    address: 'Camp Tomas Cabili, Tipanoy, Iligan City (Substations: Tambo, Nonucan, Tag-Ibo, Tubod, Poblacion)',
    description: 'Police Emergency Assistance, Law Enforcement, Public Safety, and Peace & Order across all 44 barangays.',
    isAvailable247: true,
  },
  {
    id: 'bfp-iligan',
    name: 'Bureau of Fire Protection - Iligan Central Fire Station',
    agency: 'Bureau of Fire Protection (BFP)',
    numbers: ['160', '161', '(063) 221-9055', '(063) 221-9056', '(063) 224-7726', '0967-871-4388', '0930-116-5433'],
    category: 'fire',
    address: 'Buhanginan Hills, Pala-o, Iligan City (Sub-stations: Tubod, Buru-un, Sta. Filomena, Dalipuga, San Miguel, Saray, Suarez)',
    description: 'Fire Suppression, Emergency Medical Response, Search & Rescue, and Hazardous Material Control.',
    isAvailable247: true,
  },
  {
    id: 'red-cross-iligan',
    name: 'Philippine Red Cross - Iligan City Chapter',
    agency: 'Philippine Red Cross (PRC)',
    numbers: ['(063) 222-2907', '0967-228-3196', '(063) 221-3088', '143'],
    category: 'medical',
    address: 'Rosario Heights, Brgy. Tubod, Iligan City (Beside LTO Office)',
    description: 'Emergency Blood Services, First Aid Response, Disaster Relief Logistics, and 24/7 Ambulance Dispatch.',
    isAvailable247: true,
  },
  {
    id: 'pcg-iligan',
    name: 'Philippine Coast Guard (PCG) - CGS Lanao del Norte / Sub-Station Iligan',
    agency: 'Philippine Coast Guard (PCG)',
    numbers: ['(063) 211-5398', '0917-640-2326', '0917-724-3682', '0905-388-7551'],
    category: 'rescue',
    address: 'Port of Iligan, Saray / Poblacion Coastal Area, Iligan City',
    description: 'Maritime Search & Rescue, Coastal Flood Evacuation, Sea Travel Advisories, and Marine Environmental Protection.',
    isAvailable247: true,
  },
  {
    id: 'gcmh-hospital',
    name: 'Gregorio T. Lluch Memorial Hospital (GTLMH - City Hospital)',
    agency: 'Iligan City Public Hospital',
    numbers: ['(063) 221-2536', '(063) 221-9906', '(063) 221-2522', '(063) 221-2523'],
    category: 'medical',
    address: 'Tala-id, Tubod, Iligan City',
    description: 'Primary Public Tertiary Hospital, 24/7 Emergency Room, Trauma Care, and Mass Casualty Incident Center.',
    isAvailable247: true,
  },
  {
    id: 'adventist-hospital',
    name: 'Adventist Medical Center Iligan (Sanitarium)',
    agency: 'Adventist Healthcare System',
    numbers: ['(063) 221-3636', '(063) 221-7199', '(063) 221-3029'],
    category: 'medical',
    address: 'Andres Bonifacio Ave, San Miguel, Iligan City',
    description: 'Private Tertiary Hospital with 24/7 Emergency Room, ICU, and Ambulance Care.',
    isAvailable247: true,
  },
  {
    id: 'dr-uy-hospital',
    name: 'Dr. Manuel Uy Hospital & Mercy Community Hospital',
    agency: 'Private Healthcare Partners',
    numbers: ['(063) 221-3621', '(063) 228-1140', '(063) 221-2676'],
    category: 'medical',
    address: 'Roxas Ave / Camague, Iligan City',
    description: 'Emergency Medical Services, Inpatient Care, and Emergency Surgical Consultation.',
    isAvailable247: true,
  },
  {
    id: 'cho-iligan',
    name: 'City Health Office (CHO 1 & 2) & Disease Surveillance',
    agency: 'Iligan City Health Office',
    numbers: ['(063) 221-6108', '(063) 221-6174', '0928-718-1124', '0917-874-8988'],
    category: 'medical',
    address: 'City Hall Annex, Pala-o, Iligan City',
    description: 'Public Health Emergencies, Disease Surveillance, Post-Disaster Sanitation, and Medical Supplies.',
    isAvailable247: true,
  },
  {
    id: 'cswd-iligan',
    name: 'City Social Welfare & Development Office (CSWD Iligan)',
    agency: 'LGU Iligan Social Welfare',
    numbers: ['0917-505-0401', '0953-415-3151', '0955-034-0948'],
    category: 'rescue',
    address: 'City Hall Complex, Buhanginan Hills, Pala-o, Iligan City',
    description: 'Evacuation Center Management, Food Pack Distribution, Family Relief Goods, and Psycho-Social First Aid.',
    isAvailable247: true,
  },
  {
    id: 'ilpi-power',
    name: 'Iligan Light & Power Inc. (ILPI - Electrical Hazards & Restoration)',
    agency: 'ILPI Power Distribution Utility',
    numbers: ['0917-844-7071', '(063) 221-5708', '(063) 221-5709', '(063) 223-1188', '(063) 222-2777'],
    category: 'utilities',
    address: 'Bro. Jeffrey Road, Pala-o, Iligan City',
    description: '24/7 Power Dispatch for Fallen Electrical Wires, Transformer Explosions, Post-Flood Power Restoration, and Emergency Grid Isolation.',
    isAvailable247: true,
  },
  {
    id: 'icwd-water',
    name: 'Iligan City Waterworks System (ICWS - Water Supply & Rationing)',
    agency: 'Iligan City Waterworks (ICWS)',
    numbers: ['(063) 223-3233', '0945-662-6528', '0932-532-5224'],
    category: 'utilities',
    address: 'Buhanginan Hills, Pala-o, Iligan City',
    description: 'Water Main Break Emergencies, Potable Water Tanker Rationing in Evacuation Centers, and Water Line Restoration.',
    isAvailable247: false,
  },
];

export const ILIGAN_BARANGAYS: BarangayInfo[] = [
  {
    id: 'b-abuno',
    name: 'Abuno',
    district: 'South',
    populationEstimate: '~7,200',
    hazards: ['landslide', 'flash_flood'],
    evacuationCentres: ['Abuno Elementary School', 'Abuno Barangay Hall Gym'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Moderate-to-High Landslide Risk. Bungtoron nga lugar duol sa Abuno river basin; dali magdahili ang yuta panahon sa kusog nga ulan.',
      fil: 'MGB Hazard Rating: Katamtaman hanggang Mataas na Banta ng Landslide. Maburol na lugar at malapit sa ilog.',
      en: 'MGB Hazard Rating: Moderate-to-High Landslide. Hilly terrain along Abuno stream basin; susceptible to rainfall-induced landslides.',
    },
    contactPersonOrOffice: 'Abuno Barangay Disaster Committee',
  },
  {
    id: 'b-acmac',
    name: 'Acmac',
    district: 'North',
    populationEstimate: '~6,800',
    hazards: ['storm_surge', 'flood'],
    evacuationCentres: ['Acmac Elementary School', 'Acmac Multi-Purpose Center'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Coastal Storm Surge Zone. Baybayon sa hilagang Iligan; peligrosong maigo sa dakong balod ug coastal flooding panahon sa bagyo.',
      fil: 'MGB Hazard Rating: Banta ng Storm Surge at Baha sa Baybayin. Mapanganib kapag may bagyo.',
      en: 'MGB Hazard Rating: High Coastal Storm Surge. Northern coastal sector exposed to storm surge runup and tidal flooding.',
    },
    contactPersonOrOffice: 'Acmac BDRRMC Command',
  },
  {
    id: 'b-bagongsilang',
    name: 'Bagong Silang',
    district: 'Central',
    populationEstimate: '~11,500',
    hazards: ['flood', 'fire'],
    evacuationCentres: ['Bagong Silang Covered Court', 'Iligan City Central School'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Urban Drainage Flooding & Fire Hazard. Sementadong residential hub sa urban center; dali mag-overflow ang mga drainage channel.',
      fil: 'MGB Hazard Rating: Baha sa Urban Drainage at Panganib ng Sunog. Siksikang residential area.',
      en: 'MGB Hazard Rating: High Urban Street Inundation & Fire Hazard. Densely populated residential grid prone to drainage backup.',
    },
  },
  {
    id: 'b-bonbonon',
    name: 'Bonbonon',
    district: 'East',
    populationEstimate: '~4,300',
    hazards: ['landslide', 'flash_flood'],
    evacuationCentres: ['Bonbonon Primary School', 'Bonbonon Tribal Center'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: High Landslide Susceptibility Zone. Upland mountainous barangay; bantayan ang slope collapse sa steep road cuts.',
      fil: 'MGB Hazard Rating: Mataas na Panganib sa Landslide. Bundok na lugar, mag-ingat sa pagguho ng lupa.',
      en: 'MGB Hazard Rating: High Landslide Susceptibility. Upland mountain slope area with landslide risks along mountain passes.',
    },
  },
  {
    id: 'b-bunawan',
    name: 'Bunawan',
    district: 'East',
    populationEstimate: '~3,900',
    hazards: ['landslide', 'flash_flood'],
    evacuationCentres: ['Bunawan Integrated School', 'Barangay Gym'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: High Slope Instability & Flash Flood. Kabukiran nga adunay mga sapa; hatagag pagtagad ang mga pagdahili sa yuta.',
      fil: 'MGB Hazard Rating: Pagguho ng Lupa at Puno ng Sapa. Mapanganib sa panahon ng tuloy-tuloy na ulan.',
      en: 'MGB Hazard Rating: High Slope Instability & Creek Swells. Mountainous zone prone to rockfalls and ravine flash surges.',
    },
  },
  {
    id: 'b-buruun',
    name: 'Buru-un',
    district: 'South',
    populationEstimate: '~18,400',
    hazards: ['storm_surge', 'flood', 'landslide'],
    evacuationCentres: ['Buru-un School of Fisheries', 'Buru-un Multi-Purpose Gym'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Coastal Storm Surge & Highway Slope Cuts. Gateway sa timog; peligro sa coastal surge ug landslide sa highway slopes.',
      fil: 'MGB Hazard Rating: Banta ng Storm Surge at Landslide sa Highway. Baybayin sa timog ng lungsod.',
      en: 'MGB Hazard Rating: Coastal Storm Surge & Slope Collapse. Southern coastal gateway bounded by coastal bay and highway hill cuts.',
    },
  },
  {
    id: 'b-calubian',
    name: 'Calubian',
    district: 'South',
    populationEstimate: '~4,100',
    hazards: ['flood', 'flash_flood'],
    evacuationCentres: ['Calubian Elementary School'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Lowland Creek Overflow Zone. Dapit duol sa mga sapa sa habagatan; mag-evacuate kun mag-awas ang tubig.',
      fil: 'MGB Hazard Rating: Panganib sa Pagbaha mula sa Sapa. Mababang lugar sa timog.',
      en: 'MGB Hazard Rating: Lowland Stream Inundation Zone. Inland residential pockets subject to localized creek overflow.',
    },
  },
  {
    id: 'b-dalipuga',
    name: 'Dalipuga',
    district: 'North',
    populationEstimate: '~21,000',
    hazards: ['storm_surge', 'landslide', 'flood'],
    evacuationCentres: ['Dalipuga Central School', 'Dalipuga National High School Gym'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: High Coastal Surge & Mountain Slope Failure. Pinaka-amihanang coastal barangay; dakong peligro sa balod ug pagdahili.',
      fil: 'MGB Hazard Rating: Mataas na Panganib ng Storm Surge at Landslide. Pinakahilagang baybayin ng Iligan.',
      en: 'MGB Hazard Rating: High Coastal Surge & Mountain Landslide. Northernmost coastal boundary with steep background slopes.',
    },
  },
  {
    id: 'b-delcarmen',
    name: 'Del Carmen',
    district: 'Central',
    populationEstimate: '~9,200',
    hazards: ['flood', 'flash_flood'],
    evacuationCentres: ['Del Carmen Elementary School', 'St. Michael Gym'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Urban Flood Plain. Sementadong urban area sa tunga sa syudad; dali mabahaan ang mga dalan ug kabalayan.',
      fil: 'MGB Hazard Rating: Baha sa Urban Grid. Madaling bahain sa malakas na buhos ng ulan.',
      en: 'MGB Hazard Rating: Lowland Urban Floodplain. Central residential grid with quick runoff accumulation during heavy rains.',
    },
  },
  {
    id: 'b-digkilaan',
    name: 'Digkilaan',
    district: 'East',
    populationEstimate: '~6,400',
    hazards: ['flash_flood', 'landslide'],
    evacuationCentres: ['Digkilaan Elementary School', 'Digkilaan Tribal Hall'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Critical Flash Flood & Landslide Susceptibility. Upstream Mandulog river basin; peligroso kaayo sa flash flood ug landslide.',
      fil: 'MGB Hazard Rating: Lubhang Mapanganib sa Flash Flood at Landslide. Taas na bahagi ng Mandulog River basin.',
      en: 'MGB Hazard Rating: Critical Flash Flood & Severe Landslide. Upstream catchment of Mandulog River with severe surge and riverbank erosion.',
    },
  },
  {
    id: 'b-ditucalan',
    name: 'Ditucalan',
    district: 'South',
    populationEstimate: '~5,300',
    hazards: ['landslide', 'flash_flood'],
    evacuationCentres: ['Ditucalan Elementary School', 'Ditucalan Barangay Center'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Severe Slope Failure & Waterfall Basin. Bungtoron nga lugar duol sa Tinago Falls access; likayi ang mga pangpang.',
      fil: 'MGB Hazard Rating: Panganib sa Landslide at Baha. Malapit sa Tinago Falls corridor.',
      en: 'MGB Hazard Rating: High Slope Instability & Waterfall Channel. Hilly area near Tinago corridor prone to landslide blockages.',
    },
  },
  {
    id: 'b-dulag',
    name: 'Dulag',
    district: 'East',
    populationEstimate: '~2,800',
    hazards: ['landslide', 'flash_flood'],
    evacuationCentres: ['Dulag Tribal Center', 'Dulag Primary School'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Extreme Upland Landslide Zone. Remote nga kabukiran; taas nga posibilidad sa pagdahili ug pagkaputol sa dalan.',
      fil: 'MGB Hazard Rating: Lubhang Mataas na Panganib ng Landslide. Nakahiwalay na bundok na lugar.',
      en: 'MGB Hazard Rating: Extreme Upland Landslide Hazard. Isolated upland forest sector highly vulnerable to slope collapse.',
    },
  },
  {
    id: 'b-hindang',
    name: 'Hindang',
    district: 'East',
    populationEstimate: '~2,100',
    hazards: ['landslide', 'flash_flood'],
    evacuationCentres: ['Hindang Elementary School', 'Hindang Barangay Gym'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: High Mountain Landslide Susceptibility. Mountainous indigenous domain; peligro sa rockfall ug landslide sa mga agianan.',
      fil: 'MGB Hazard Rating: Mataas na Banta ng Landslide. Kabundukan at daluyan ng ilog.',
      en: 'MGB Hazard Rating: Severe Mountainous Landslide Hazard. Remote upland terrain subject to mountain road blockage and landslides.',
    },
  },
  {
    id: 'b-hinaplanon',
    name: 'Hinaplanon',
    district: 'North',
    populationEstimate: '~26,500',
    hazards: ['flood', 'flash_flood'],
    evacuationCentres: ['Hinaplanon Elementary School', 'Hinaplanon Multi-Purpose Gym'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Critical Mandulog Flash Flood Basin (Sendong Corridor). Direct river basin; taas kaayo ang peligro sa flash flood.',
      fil: 'MGB Hazard Rating: Lubhang Mapanganib sa Flash Flood (Mandulog River Basin). Mabilis tumaas ang tubig.',
      en: 'MGB Hazard Rating: Critical Mandulog River Flash Flood Basin. Prime Mandulog floodplain; severe flash flood surge hazard.',
    },
    contactPersonOrOffice: 'Hinaplanon Barangay Disaster Committee',
  },
  {
    id: 'b-kabacsanan',
    name: 'Kabacsanan',
    district: 'East',
    populationEstimate: '~3,100',
    hazards: ['landslide', 'flash_flood'],
    evacuationCentres: ['Kabacsanan Primary School', 'Kabacsanan Tribal Hall'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: High Upland Landslide Zone. High altitude mountain ridge; pagbantay sa landslide ug paspas nga baha sa sapa.',
      fil: 'MGB Hazard Rating: Mataas na Panganib ng Landslide sa Bundok.',
      en: 'MGB Hazard Rating: High Altitude Landslide & Ravine Surge Hazard. High mountain plateau with steep river gorges.',
    },
  },
  {
    id: 'b-kalilangan',
    name: 'Kalilangan',
    district: 'East',
    populationEstimate: '~2,600',
    hazards: ['landslide', 'flash_flood'],
    evacuationCentres: ['Kalilangan Tribal Center'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Moderate-to-High Landslide Risk. Kabukiran ug gihawiran sa sapa; bantayan ang pag-anam kausab sa yuta.',
      fil: 'MGB Hazard Rating: Panganib ng Pagguho ng Lupa at Baha.',
      en: 'MGB Hazard Rating: Moderate-to-High Landslide Susceptibility. Interior mountain slopes with creek flash swelling risks.',
    },
  },
  {
    id: 'b-kiwalan',
    name: 'Kiwalan',
    district: 'North',
    populationEstimate: '~13,800',
    hazards: ['storm_surge', 'flood', 'landslide'],
    evacuationCentres: ['Kiwalan Elementary School', 'Kiwalan Barangay Gym'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Coastal Surge & Hillside Slope Failure. Baybayon ug pangpang sa amihanan; peligro sa dakong balod ug landslide.',
      fil: 'MGB Hazard Rating: Banta ng Storm Surge at Pagguho sa Gilid ng Bundok.',
      en: 'MGB Hazard Rating: Coastal Surge & Steep Hillside Hazard. Northern coastal strip bounded by steep mountain backdrops.',
    },
  },
  {
    id: 'b-luinab',
    name: 'Luinab',
    district: 'Central',
    populationEstimate: '~12,400',
    hazards: ['flood', 'flash_flood'],
    evacuationCentres: ['Luinab Elementary School', 'Luinab Covered Court'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Inland Drainage Basin. Low-lying residential valley; madali ang pagtigum sa tubig-ulan gikan sa mga bungtod.',
      fil: 'MGB Hazard Rating: Baha sa Mababang Lugar. Natipong tubig mula sa burol.',
      en: 'MGB Hazard Rating: Inland Drainage Catchment Basin. Lowland residential valley susceptible to runoff accumulation.',
    },
  },
  {
    id: 'b-mahayahay',
    name: 'Mahayahay',
    district: 'Central',
    populationEstimate: '~7,900',
    hazards: ['flood', 'flash_flood'],
    evacuationCentres: ['Mahayahay Elementary School', 'Iligan City Central School'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Lowland River Overflow Zone. Punoan sa Iligan River stream channels; peligro sa baha kun mag-overflow ang suba.',
      fil: 'MGB Hazard Rating: Panganib ng Pagbaha mula sa Iligan River.',
      en: 'MGB Hazard Rating: Lowland River Channel Overflow. Central urban sector adjoining Iligan River distributaries.',
    },
  },
  {
    id: 'b-mainit',
    name: 'Mainit',
    district: 'South',
    populationEstimate: '~3,800',
    hazards: ['landslide', 'flash_flood'],
    evacuationCentres: ['Mainit Elementary School'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Thermal Spring Terrain Landslide Risk. Geothermal hill zone; mag-ingat sa pagdahili sa yuta sa bakilid.',
      fil: 'MGB Hazard Rating: Panganib ng Landslide sa Maburol na Lugar.',
      en: 'MGB Hazard Rating: Thermal Spring Terrain Landslide Risk. Hilly interior zone prone to slope erosion and flash creek surges.',
    },
  },
  {
    id: 'b-mandulog',
    name: 'Mandulog',
    district: 'North',
    populationEstimate: '~14,200',
    hazards: ['flash_flood', 'landslide'],
    evacuationCentres: ['Mandulog Primary School', 'Barangay Covered Court'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: High Mandulog River Flash Flood Zone. Riverbank communities; paspas nga pagtaas sa tubig panahon sa kusog nga ulan sa kabukiran.',
      fil: 'MGB Hazard Rating: Mataas na Banta ng Flash Flood sa Mandulog River.',
      en: 'MGB Hazard Rating: Severe Mandulog River Flash Flood Zone. Main river channel corridor with high water surge velocity.',
    },
  },
  {
    id: 'b-mariacristina',
    name: 'Maria Cristina',
    district: 'South',
    populationEstimate: '~12,800',
    hazards: ['flash_flood', 'landslide'],
    evacuationCentres: ['Maria Cristina Elementary School', 'National High School Gym'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Hydro Spillway & Agus River Floodplain. Duol sa Agus River ug Maria Cristina Falls; paminaw sa dam spillway advisories.',
      fil: 'MGB Hazard Rating: Banta ng Baha sa Agus River at Hydro Spillway.',
      en: 'MGB Hazard Rating: Agus River Spillway & Hydroelectric Floodplain. Direct influence zone of NPC/LGU dam release advisories.',
    },
  },
  {
    id: 'b-palao',
    name: 'Pala-o',
    district: 'Central',
    populationEstimate: '~15,100',
    hazards: ['flood', 'fire'],
    evacuationCentres: ['City Central School', 'Iligan City National High School Gym'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Commercial Core Urban Inundation & Fire Risk. Market/commercial district; street flooding at major intersections.',
      fil: 'MGB Hazard Rating: Baha sa Komersyal na Sentro at Sunog.',
      en: 'MGB Hazard Rating: Urban Commercial Drainage Flooding & High Fire Hazard. Central commercial zone with heavy traffic and dense structures.',
    },
  },
  {
    id: 'b-panoroganan',
    name: 'Panoroganan',
    district: 'East',
    populationEstimate: '~2,200',
    hazards: ['landslide', 'flash_flood'],
    evacuationCentres: ['Panoroganan Tribal Gym', 'Primary School'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: High Upland Mountain Landslide Risk. Remote tribal barangay; taas nga peligro sa pagkaputol sa dalan gumikan sa pagdahili.',
      fil: 'MGB Hazard Rating: Mataas na Panganib sa Pagguho ng Lupa sa Bundok.',
      en: 'MGB Hazard Rating: Extreme Upland Slope Collapse Hazard. Remote indigenous mountain territory with severe landslide isolation risk.',
    },
  },
  {
    id: 'b-poblacion',
    name: 'Poblacion',
    district: 'Central',
    populationEstimate: '~5,200',
    hazards: ['flood', 'fire'],
    evacuationCentres: ['Iligan City Central School', 'Public Market Annex Gym'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: River Delta Urban Inundation. Historic city proper duol sa gawasanan sa Iligan River ug dagat.',
      fil: 'MGB Hazard Rating: Baha sa Delta ng Ilog at Sentro ng Lungsod.',
      en: 'MGB Hazard Rating: Estuarine River Delta Inundation Zone. Historic urban heart at Iligan River mouth, influenced by high tide.',
    },
  },
  {
    id: 'b-pugaan',
    name: 'Puga-an',
    district: 'East',
    populationEstimate: '~8,900',
    hazards: ['flash_flood', 'landslide'],
    evacuationCentres: ['Puga-an Elementary School', 'Puga-an Barangay Hall'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Puga-an River Flash Flood Corridor. River valley area; peligro sa paspas nga pagbaha ug landslide sa bakilid.',
      fil: 'MGB Hazard Rating: Banta ng Flash Flood sa Puga-an River Valley.',
      en: 'MGB Hazard Rating: Puga-an River Flash Flood & Landslide Basin. Catchment corridor susceptible to sudden headwater surges.',
    },
  },
  {
    id: 'b-rogongon',
    name: 'Rogongon',
    district: 'East',
    populationEstimate: '~6,900',
    hazards: ['landslide', 'flash_flood'],
    evacuationCentres: ['Rogongon Tribal Gym', 'Rogongon Central School'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Extreme Upland Landslide & Ravine Surge Zone. Pinakadako ug labing taas nga kabukiran sa Iligan.',
      fil: 'MGB Hazard Rating: Lubhang Mataas na Panganib ng Landslide sa Kabundukan.',
      en: 'MGB Hazard Rating: Severe Upland Landslide & Flash Ravine Hazard. Largest mountain barangay in Iligan with extensive slope collapse risks.',
    },
  },
  {
    id: 'b-sanantonio',
    name: 'San Antonio',
    district: 'South',
    populationEstimate: '~4,800',
    hazards: ['flood', 'landslide'],
    evacuationCentres: ['San Antonio Elementary School'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Hilly Residential Slope Failure. Habagatan nga bungtod; peligro sa localized landslide ug baha sa sapa.',
      fil: 'MGB Hazard Rating: Panganib ng Landslide at Pagbaha sa Sapa.',
      en: 'MGB Hazard Rating: Rolling Hills Slope Instability. Southern residential slope zone with localized stream flood potential.',
    },
  },
  {
    id: 'b-sanmiguel',
    name: 'San Miguel',
    district: 'Central',
    populationEstimate: '~11,300',
    hazards: ['flood', 'flash_flood'],
    evacuationCentres: ['San Miguel High School', 'San Miguel Barangay Gym'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Urban Drainage Overflow & Stream Swell. Urban residential area adjacent to Hinaplanon drainage corridors.',
      fil: 'MGB Hazard Rating: Baha sa Drainage at Sapa sa Urban Basin.',
      en: 'MGB Hazard Rating: Urban Basin Inundation. High residential density adjoining flood spillway channels.',
    },
  },
  {
    id: 'b-sanroque',
    name: 'San Roque',
    district: 'South',
    populationEstimate: '~5,600',
    hazards: ['flood', 'landslide'],
    evacuationCentres: ['San Roque Elementary School'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Rolling Slope Landslide & Stream Surge. Habagatan nga sektor; mag-amping sa pagdahili sa yuta sa bakilid.',
      fil: 'MGB Hazard Rating: Panganib ng Landslide at Baha sa Maburol na Lugar.',
      en: 'MGB Hazard Rating: Rolling Terrain Slope Collapse. Southern sector with slope cuts vulnerable to rain-induced slumping.',
    },
  },
  {
    id: 'b-santaelena',
    name: 'Santa Elena',
    district: 'North',
    populationEstimate: '~10,900',
    hazards: ['flood', 'flash_flood'],
    evacuationCentres: ['Santa Elena Elementary School', 'Barangay Covered Court'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Mandulog Lower Delta Floodplain. Lowland floodplain near Mandulog delta; dali magbaha kun mag-overflow ang suba.',
      fil: 'MGB Hazard Rating: Baha sa Lower Mandulog River Delta.',
      en: 'MGB Hazard Rating: Mandulog River Estuarine Delta Inundation Zone. Flat floodplain highly susceptible to river backwater.',
    },
  },
  {
    id: 'b-santafilomena',
    name: 'Santa Filomena',
    district: 'North',
    populationEstimate: '~16,700',
    hazards: ['flood', 'storm_surge'],
    evacuationCentres: ['Santa Filomena National High School', 'Elementary School'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: High Coastal Storm Surge & Highway Creek Overflow. Coastal highway zone; mag-evacuate kun mag-abot ang bagyo.',
      fil: 'MGB Hazard Rating: Mataas na Banta ng Storm Surge at Baha sa Baybayin.',
      en: 'MGB Hazard Rating: High Coastal Storm Surge & River Outlet Inundation. Northern coastal arterial strip prone to storm waves.',
    },
  },
  {
    id: 'b-santiago',
    name: 'Santiago',
    district: 'Central',
    populationEstimate: '~4,500',
    hazards: ['flood', 'storm_surge'],
    evacuationCentres: ['Santiago Elementary School', 'Barangay Gym'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Coastal River Mouth Inundation Zone. Urban coastal barangay at Iligan Bay; peligro sa storm surge ug tidal flood.',
      fil: 'MGB Hazard Rating: Baha at Storm Surge sa Baybayin ng Iligan Bay.',
      en: 'MGB Hazard Rating: Coastal River Mouth Surge Zone. Estuarine urban coastal sector vulnerable to storm tide inundation.',
    },
  },
  {
    id: 'b-santorosario',
    name: 'Santo Rosario',
    district: 'South',
    populationEstimate: '~6,100',
    hazards: ['flood', 'flash_flood'],
    evacuationCentres: ['Santo Rosario Covered Court'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Lowland Stream Inundation. Residensyal sa habagatan; mag-unang evacuate kun magpadayon ang kusog nga ulan.',
      fil: 'MGB Hazard Rating: Baha mula sa Inundation ng Sapa.',
      en: 'MGB Hazard Rating: Lowland Stream Drainage Inundation. Southern urban basin susceptible to localized storm runoff pooling.',
    },
  },
  {
    id: 'b-suarez',
    name: 'Suarez',
    district: 'South',
    populationEstimate: '~22,100',
    hazards: ['flood', 'landslide'],
    evacuationCentres: ['Suarez Central School', 'Suarez Multi-Purpose Gym'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Industrial Corridor Flood & Hillside Slide. Habagatan nga industrial hub; peligro sa baha sa sapa ug landslide sa bungtod.',
      fil: 'MGB Hazard Rating: Baha sa Sapa at Landslide sa Maburol na Lugar.',
      en: 'MGB Hazard Rating: Industrial Corridor Inundation & Hillside Instability. Major southern population center with creek and slope risks.',
    },
  },
  {
    id: 'b-tambacan',
    name: 'Tambacan',
    district: 'Central',
    populationEstimate: '~19,800',
    hazards: ['flood', 'flash_flood', 'storm_surge'],
    evacuationCentres: ['Tambacan Elementary School', 'Tambacan Barangay Gym'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Severe Coastal Surge & Iligan River Outlet Floodplain. Coastal & river outlet; taas kaayo ang peligro sa baha ug storm surge.',
      fil: 'MGB Hazard Rating: Lubhang Mapanganib sa Storm Surge at Baha sa Ilog.',
      en: 'MGB Hazard Rating: Severe Estuarine Storm Surge & River Outflow Hazard. High-density coastal river mouth community.',
    },
  },
  {
    id: 'b-tibanga',
    name: 'Tibanga',
    district: 'North',
    populationEstimate: '~24,300',
    hazards: ['flood', 'flash_flood'],
    evacuationCentres: ['MSU-IIT Gym', 'Tibanga Elementary School'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Urban Drainage Basin (MSU-IIT Corridor). University & commercial district; flash street flooding during thunderstorm downpours.',
      fil: 'MGB Hazard Rating: Baha sa Dalan ug Drainage sa Sentro ng Sektor ng Eskwelahan.',
      en: 'MGB Hazard Rating: Major Urban University Corridor Inundation. Dense commercial/institutional area subject to street water accumulation.',
    },
  },
  {
    id: 'b-tipanoy',
    name: 'Tipanoy',
    district: 'South',
    populationEstimate: '~17,200',
    hazards: ['flash_flood', 'landslide'],
    evacuationCentres: ['Tipanoy Elementary School', 'ICPO Camp Gym'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Tipanoy River Basin Flash Flood & Slope Failure. Valley terrain bounded by rolling hills; dangerous river swells.',
      fil: 'MGB Hazard Rating: Banta ng Flash Flood sa Tipanoy River at Landslide.',
      en: 'MGB Hazard Rating: Tipanoy River Valley Flash Surge & Road Cut Landslide. Valley corridor prone to river flash floods.',
    },
  },
  {
    id: 'b-tomascabili',
    name: 'Tomas Cabili',
    district: 'South',
    populationEstimate: '~25,900',
    hazards: ['flood', 'storm_surge', 'fire'],
    evacuationCentres: ['Tomas Cabili National High School', 'Scania Covered Court'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Coastal Industrial Surge & High Density Fire Risk. Coastal industrial and residential hub; storm surge and inundation hazard.',
      fil: 'MGB Hazard Rating: Storm Surge sa Baybayin, Baha at Banta ng Sunog.',
      en: 'MGB Hazard Rating: Coastal Industrial Storm Surge & Urban Fire Risk. Highly populated coastal industrial zone.',
    },
  },
  {
    id: 'b-tubod',
    name: 'Tubod',
    district: 'Central',
    populationEstimate: '~33,100',
    hazards: ['flood', 'flash_flood'],
    evacuationCentres: ['Tubod Elementary School', 'Overland Transport Terminal Gym'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Lower Iligan River Inundation Floodplain. Transport hub and dense urban basin; high vulnerability during river swelling + high tide.',
      fil: 'MGB Hazard Rating: Mataas na Panganib ng Pagbaha sa Lower Iligan River.',
      en: 'MGB Hazard Rating: Lower Iligan River Inundation Floodplain. Primary transport hub zone highly exposed to river channel swelling.',
    },
  },
  {
    id: 'b-ubaldolaya',
    name: 'Ubaldo Laya',
    district: 'Central',
    populationEstimate: '~16,300',
    hazards: ['flood', 'flash_flood'],
    evacuationCentres: ['Ubaldo Laya Elementary School', 'Barangay Gym'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Lowland Residential Basin. Densely built flat terrain; quick urban runoff pooling during localized rainfall.',
      fil: 'MGB Hazard Rating: Baha sa Mababang Lugar ng Pamayanan.',
      en: 'MGB Hazard Rating: Lowland Flat Residential Catchment. High-density residential zone prone to rapid urban street inundation.',
    },
  },
  {
    id: 'b-upperhinaplanon',
    name: 'Upper Hinaplanon',
    district: 'North',
    populationEstimate: '~11,800',
    hazards: ['flash_flood', 'landslide'],
    evacuationCentres: ['Upper Hinaplanon Elementary School', 'Barangay Covered Court'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Critical Mandulog Upstream Channel Flash Surge. Direct Mandulog River channel corridor; severe riverbank erosion and flash floods.',
      fil: 'MGB Hazard Rating: Lubhang Mapanganib sa Flash Flood ng Mandulog River.',
      en: 'MGB Hazard Rating: Critical Mandulog River Upstream Flash Flood Corridor. High surge velocity and riverbank erosion risk.',
    },
  },
  {
    id: 'b-uppertominobo',
    name: 'Upper Tominobo',
    district: 'South',
    populationEstimate: '~7,400',
    hazards: ['landslide', 'flash_flood'],
    evacuationCentres: ['Upper Tominobo Primary School', 'Barangay Center'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Hilly Terrain Slope Failure & Creek Surge. Bungtoron nga dapit sa habagatan; bantayan ang pagdahili sa yuta.',
      fil: 'MGB Hazard Rating: Panganib ng Landslide sa Maburol na Lugar.',
      en: 'MGB Hazard Rating: Hilly Sector Slope Failure & Ravine Swells. Southern elevated residential area susceptible to slope slumping.',
    },
  },
  {
    id: 'b-villaverde',
    name: 'Villa Verde',
    district: 'Central',
    populationEstimate: '~8,100',
    hazards: ['flood', 'fire'],
    evacuationCentres: ['Villa Verde Covered Court', 'Iligan City Central School'],
    keyRiskNotes: {
      ceb: 'MGB Hazard Rating: Urban Subdivision Street Inundation. Sementadong subdivision area sa tunga sa syudad; localized street drainage flooding.',
      fil: 'MGB Hazard Rating: Baha sa Kalsada ng Subdivision at Sunog.',
      en: 'MGB Hazard Rating: Urban Subdivision Inundation & Fire Hazard. Central residential subdivision zone with localized road pooling.',
    },
  },
];

export const HAZARD_GUIDES: HazardGuide[] = [
  {
    id: 'h-flood',
    title: {
      ceb: 'Baha ug Flash Flood sa Iligan',
      fil: 'Baha at Flash Flood sa Iligan',
      en: 'Flooding & Flash Floods in Iligan',
    },
    hazardType: 'flooding',
    icon: 'Waves',
    summary: {
      ceb: 'Ang Iligan adunay pito ka dagkong suba (sama sa Mandulog ug Iligan River). Kun mag-overflow kini, paspas kaayo ang pagtaas sa tubig.',
      fil: 'May 7 pangunahing ilog ang Iligan (tulad ng Mandulog at Iligan River). Kapag umapaw, mabilis tumaas ang tubig.',
      en: 'Iligan City is bounded by major river systems. Flash floods can occur rapidly during prolonged upland heavy rain.',
    },
    beforeSteps: [
      {
        ceb: 'I-andam ang Family Emergency Go-Bag (tubig, pagkaon, radyo, powerbank, tambal).',
        fil: 'Ihanda ang Emergency Go-Bag.',
        en: 'Prepare household Go-Bag with 3 days of non-perishable food, water, and first aid.',
      },
      {
        ceb: 'Aron makadawat og pahibalo, subaya ang official Iligan CDRRMO ug PAGASA weather updates.',
        fil: 'Subaybayan ang CDRRMO at PAGASA updates.',
        en: 'Monitor official Iligan CDRRMO and PAGASA rainfall advisories continuously.',
      },
      {
        ceb: 'Hibaloa ang opisyal nga evacuation center sa inyong barangay.',
        fil: 'Alamin ang pinakamalapit na evacuation center.',
        en: 'Identify your designated barangay evacuation center and safe routes.',
      },
    ],
    duringSteps: [
      {
        ceb: 'KUN PASPAS ANG PAGTAAS SA TUBIG: Mobakwit dayon ngadto sa mas taas ug luwas nga lugar.',
        fil: 'KAPAG MABILIS ANG TAAS NG TUBIG: Lumikas agad sa mataas na lugar.',
        en: 'IF WATER RISES RAPIDLY: Evacuate immediately to higher ground or second story.',
      },
      {
        ceb: 'Palonga ang main switch sa kuryente kun luwas buhaton sa wala pa moabot ang tubig.',
        fil: 'Patayin ang main power switch kung ligtas gawin.',
        en: 'Turn off main electrical circuit breaker if safe before floodwater reaches outlets.',
      },
      {
        ceb: 'AYAW paglusong sa kusog o lawom nga tubig-baha o mag-drive sa nagdalagan nga baha.',
        fil: 'HUWAG lumusong sa mabilis o malalim na baha.',
        en: 'NEVER walk or drive through moving floodwaters.',
      },
    ],
    afterSteps: [
      {
        ceb: 'Pabilin sa evacuation center hangtod nga opisyal nga ideklara sa CDRRMO nga luwas na.',
        fil: 'Manatili sa evacuation center hanggang maging ligtas ayon sa CDRRMO.',
        en: 'Remain in safe shelter until CDRRMO issues an official all-clear signal.',
      },
      {
        ceb: 'Pag-amping sa nagbitay nga linya sa kuryente ug kontaminadong tubig-baha.',
        fil: 'Mag-ingat sa mga naputol na kable ng kuryente.',
        en: 'Watch out for downed power lines and contaminated floodwater.',
      },
    ],
    safetyTip: {
      ceb: 'Tandaan: Sa baha sa Iligan, unaha ang kinabuhi kaysa gamit!',
      fil: 'Tandaan: Una ang buhay kaysa sa gamit!',
      en: 'Remember: Life safety always comes ahead of personal property!',
    },
  },
  {
    id: 'h-earthquake',
    title: {
      ceb: 'Linog (Earthquake Safety)',
      fil: 'Linog (Earthquake Safety)',
      en: 'Earthquake Safety & Preparedness',
    },
    hazardType: 'earthquake',
    icon: 'Activity',
    summary: {
      ceb: 'Ang linog walay gipiling oras ug dili ma-predict. Sunda ang standard DROP, COVER, ug HOLD.',
      fil: 'Hindi mahuhulaan ang linog. Sundin ang DROP, COVER, at HOLD.',
      en: 'Earthquakes happen without advance warning. Execute Drop, Cover, and Hold immediately.',
    },
    beforeSteps: [
      {
        ceb: 'I-secure ang bug-at nga kabinet, appliances, ug salamin sa bongbong.',
        fil: 'I-secure ang mabibigat na kasangkapan.',
        en: 'Anchor heavy furniture, appliances, and wall hangings firmly.',
      },
      {
        ceb: 'Aron dili matrap, hibaloa ang duha ka dali nga agianan paingon sa gawas sa balay.',
        fil: 'Alamin ang exit routes sa inyong bahay.',
        en: 'Identify clear exit paths and safe outdoor open spaces.',
      },
    ],
    duringSteps: [
      {
        ceb: 'PANIYUKO (DROP): Paniyuko dayon sa salog sa imong mga kamot ug tuhod.',
        fil: 'PUMAYUKO (DROP): Pumayuko agad sa sahig.',
        en: 'DROP onto your hands and knees.',
      },
      {
        ceb: 'SUMILONG (COVER): Sumilong ilawom sa lig-on nga lamesa ug protektahi ang ulo ug liog.',
        fil: 'LUMILONG (COVER): Lumilong sa ilalim ng matibay na mesa.',
        en: 'COVER your head and neck under a sturdy table or desk.',
      },
      {
        ceb: 'KAPOT (HOLD ON): Kapot sa lamesa hangtod mohunong ang pag-uyog.',
        fil: 'KUMAPOT (HOLD ON): Kumapot sa mesa hanggang huminto ang pag-alon.',
        en: 'HOLD ON to your shelter until shaking stops completely.',
      },
      {
        ceb: 'Kung anaa sa gawas, palayo sa mga building, poste sa kuryente, ug pader.',
        fil: 'Kung nasa labas, lumayo sa mga gusali at poste.',
        en: 'If outdoors, move away from buildings, streetlights, and utility wires.',
      },
    ],
    afterSteps: [
      {
        ceb: 'Pag-andam sa posibleng aftershocks gikan sa PHIVOLCS updates.',
        fil: 'Maghanda para sa mga pag-uga o aftershocks.',
        en: 'Be prepared for subsequent aftershocks.',
      },
      {
        ceb: 'Susiha kun naay aksidente o kadaot sa balay sa wala pa mosulod usab.',
        fil: 'Suriin ang pinsala bago pumasok muli.',
        en: 'Inspect home for structural damage or gas leaks before re-entering.',
      },
    ],
    safetyTip: {
      ceb: 'Ayaw paggamit og elevator ug ayaw pagdagan samtang nag-uyog pa ang yuta!',
      fil: 'Huwag gumamit ng elevator habang nag-uuga!',
      en: 'Never use elevators during or immediately after a tremor!',
    },
  },
  {
    id: 'h-typhoon',
    title: {
      ceb: 'Bagyo ug Kusog nga Ulan (Typhoon Preparedness)',
      fil: 'Bagyo at Malakas na Ulan',
      en: 'Typhoon & Heavy Weather Safety',
    },
    hazardType: 'typhoon',
    icon: 'CloudLightning',
    summary: {
      ceb: 'Panahon sa tropical cyclone, ang Iligan makasinati og kusog nga hangin, pag-ulan, ug posibleng pagbaha o pagdahili sa yuta.',
      fil: 'Sa panahon ng bagyo, nararanasan ang malakas na hangin at ulan.',
      en: 'Typhoons bring heavy rainfall, gale-force winds, and increased risk of floods and landslides.',
    },
    beforeSteps: [
      {
        ceb: 'I-check ang mga atop ug kahoy sa palibot. I-secure o putla ang peligroso nga sanga.',
        fil: 'Magsagawa ng pagsusuri sa bubong at mga puno.',
        en: 'Inspect and trim tree branches near powerlines and reinforce loose roof sheets.',
      },
      {
        ceb: 'I-charge ang tanang cellphone, powerbank, ug dako nga flashlight.',
        fil: 'I-charge ang mga gadget at powerbank.',
        en: 'Fully charge mobile devices, powerbanks, and emergency lamps.',
      },
    ],
    duringSteps: [
      {
        ceb: 'Pabilin sa sulod sa luwas ug sirado nga balay o evacuation center.',
        fil: 'Manatili sa loob ng bahay o evacuation center.',
        en: 'Stay inside a sturdy structure or official evacuation shelter.',
      },
      {
        ceb: 'Palayo sa bintana nga salamin kun kusog kaayo ang hangin.',
        fil: 'Lumayo sa mga bintanang salamin.',
        en: 'Stay away from glass windows and light roofs.',
      },
    ],
    afterSteps: [
      {
        ceb: 'Pag-amping sa natagak nga kable ug sirada nga dalan sa Iligan.',
        fil: 'Mag-ingat sa mga nakalaylay na kable.',
        en: 'Beware of fallen electric cables and damaged roads.',
      },
    ],
    safetyTip: {
      ceb: 'Sunda ang official Tropical Cyclone Wind Signal (TCWS) gikan sa DOST-PAGASA!',
      fil: 'Sundin ang opisyal na TCWS mula sa PAGASA!',
      en: 'Follow official Tropical Cyclone Warning Signals issued by DOST-PAGASA!',
    },
  },
  {
    id: 'h-landslide',
    title: {
      ceb: 'Pagdahili sa Yuta (Landslide Risk)',
      fil: 'Pagdahili ng Lupa (Landslide)',
      en: 'Landslide Hazards & Warnings',
    },
    hazardType: 'landslide',
    icon: 'Mountain',
    summary: {
      ceb: 'Ang mga bungtoron nga barangay sa Iligan (Rogongon, Ditucalan, Mandulog, Kiwalan) adunay peligro sa pagdahili sa yuta human sa taas nga pag-ulan.',
      fil: 'Ang mga maburol na barangay ay may panganib sa pagdahili ng lupa.',
      en: 'Hilly and mountainous barangays of Iligan are vulnerable to slope failures after continuous rain.',
    },
    beforeSteps: [
      {
        ceb: 'Bantayi ang mga timailhan: gisi sa yuta, pag-usab sa agas sa tubod, o pagkadungog og hungihong sa bukid.',
        fil: 'Mag-ingat sa mga lamat sa lupa o pagbabago sa agos ng tubig.',
        en: 'Watch for warning signs: ground cracks, sudden muddy water flow, or rumbling hillside sounds.',
      },
    ],
    duringSteps: [
      {
        ceb: 'Kun naay pagdahili, dagan padulong sa kilid o sa mas luwas nga patag nga lugar. Ayaw pagpaingon sa dalan sa yuta.',
        fil: 'Umalis agad patungo sa ligtas at patag na lugar.',
        en: 'Evacuate perpendicular to the direction of the slide to open ground.',
      },
    ],
    afterSteps: [
      {
        ceb: 'Ayaw pagduol sa dapit nga nahitaboan sa landslide kay mahimong masundan pa kini.',
        fil: 'Huwag lumapit sa lugar ng landslide.',
        en: 'Stay away from the slide area. Secondary slides can occur unexpectedly.',
      },
    ],
    safetyTip: {
      ceb: 'Sa pagnipis sa yuta panahon sa kusog nga ulan, mag-evacuate na daan sa dili pa mag gabii!',
      fil: 'Lumikas nang maaga bago gumabi sa mga delikadong lugar!',
      en: 'In high landslide hazard zones, evacuate early before nightfall!',
    },
  },
];

export const GO_BAG_ITEMS: GoBagItem[] = [
  {
    id: 'gb-water',
    category: 'water_food',
    title: {
      ceb: 'Tubig Mainom (Atleast 1 gallon kada tao matag adlaw, 3 ka adlaw)',
      fil: 'Tubig na maiinom (1 gallon bawat tao kada araw, para sa 3 araw)',
      en: 'Drinking Water (at least 1 gallon per person per day for 3 days)',
    },
    description: {
      ceb: 'Importante kaayo alang sa hydration ug paglikay sa sakit.',
      fil: 'Pinakamahalaga para sa kalusugan.',
      en: 'Essential for hydration and emergency sanitation.',
    },
    checked: false,
    isEssential: true,
  },
  {
    id: 'gb-food',
    category: 'water_food',
    title: {
      ceb: 'Ready-to-eat Canned Goods & Easy Open Snacks',
      fil: 'Pagkaong lata at di-napapanis na pagkain',
      en: 'Non-perishable Food & Ready-to-eat Meals (3-day supply)',
    },
    description: {
      ceb: 'Lata nga dili kinahanglan og can opener, biscuit, mani.',
      fil: 'Mabilis kainin nang hindi na kailangang lutuin.',
      en: 'Nutritious items that require no cooking or refrigeration.',
    },
    checked: false,
    isEssential: true,
  },
  {
    id: 'gb-firstaid',
    category: 'first_aid',
    title: {
      ceb: 'Basic First Aid Kit (Bandage, Alcohol, Gauze, Betadine)',
      fil: 'First Aid Kit (Gasa, Alcohol, Gamot)',
      en: 'Comprehensive First Aid Kit & Antiseptics',
    },
    description: {
      ceb: 'Alang sa pagtambal sa minor nga samad ug garas.',
      fil: 'Para sa mga sugat at paunang lunas.',
      en: 'Bandages, antiseptic solution, burn ointment, and sterile gauze.',
    },
    checked: false,
    isEssential: true,
  },
  {
    id: 'gb-meds',
    category: 'first_aid',
    title: {
      ceb: 'Maintainance Medicines & Painkillers (Paracetamol, Maintenance)',
      fil: 'Maintenance na gamot at paracetamol',
      en: 'Personal Maintenance Medications & Essential Medicines',
    },
    description: {
      ceb: 'Pirme nga tambal sa hupang, altapresyon, pampahuway, o diabetes.',
      fil: 'Maging handa ng sapat na gamot para sa 7 araw.',
      en: 'Include at least a 7-day supply of prescription medicines.',
    },
    checked: false,
    isEssential: true,
  },
  {
    id: 'gb-flashlight',
    category: 'tools_gear',
    title: {
      ceb: 'Waterproof Flashlight & Extra Batteries / Solar Lamp',
      fil: 'Flashlight at sobrang baterya',
      en: 'Heavy-duty Flashlight / Headlamp & Spare Batteries',
    },
    description: {
      ceb: 'Incasong maputol ang kuryente o mag-evacuate sa gabi.',
      fil: 'Para sa pagkawala ng kuryente.',
      en: 'Crucial during power outages and nighttime evacuation.',
    },
    checked: false,
    isEssential: true,
  },
  {
    id: 'gb-powerbank',
    category: 'tools_gear',
    title: {
      ceb: 'Powerbank (Fully charged) & Cellphone Cables',
      fil: 'Powerbank at charger cables',
      en: 'Fully Charged High-Capacity Power Bank & Charging Cables',
    },
    description: {
      ceb: 'Aron makapabilin nga konektado sa pamilya ug CDRRMO announcements.',
      fil: 'Upang makatanggap ng mga tawag at mensahe ng saklolo.',
      en: 'Keep cellular phones powered to receive emergency alerts.',
    },
    checked: false,
    isEssential: true,
  },
  {
    id: 'gb-whistle',
    category: 'tools_gear',
    title: {
      ceb: 'Whistle / Pito (Alang sa pagpangayog tabang)',
      fil: 'Pito para sa paghingi ng tulong',
      en: 'Loud Emergency Whistle (For signalling rescue)',
    },
    description: {
      ceb: 'Dali nga makatabang sa mga responders sa pagpangita kaninyo.',
      fil: 'Mas malakas kaysa sa sigaw upang marinig ng rescuer.',
      en: 'Loud acoustics require less energy than shouting to signal rescuers.',
    },
    checked: false,
    isEssential: true,
  },
  {
    id: 'gb-radio',
    category: 'tools_gear',
    title: {
      ceb: 'Portable Battery or Solar Powered AM/FM Radio',
      fil: 'Portable Radio na may baterya',
      en: 'Battery-Powered Portable AM/FM Radio',
    },
    description: {
      ceb: 'Aron makadawat og balita kun maputol ang signal sa cellular ug internet.',
      fil: 'Makinig sa mga opisyal na balita.',
      en: 'Receive official broadcasts when mobile networks are down.',
    },
    checked: false,
    isEssential: false,
  },
  {
    id: 'gb-documents',
    category: 'documents_cash',
    title: {
      ceb: 'Importante nga Dokumento sa Waterproof Bag (IDs, Birth Cert, Land Title)',
      fil: 'Mahahalagang Dokumento sa Waterproof Bag',
      en: 'Important Documents Sealed in Waterproof Bag',
    },
    description: {
      ceb: 'IDs, birth certificates, insurance, vaccination cards.',
      fil: 'Sertipiko ng kapanganakan, kontrata, at mga ID.',
      en: 'Photocopies and digital backups of government IDs, birth certificates, deeds.',
    },
    checked: false,
    isEssential: true,
  },
  {
    id: 'gb-cash',
    category: 'documents_cash',
    title: {
      ceb: 'Kuwarta / Cash sa Gagmay nga Bill',
      fil: 'Cash o pera sa maliliit na papel',
      en: 'Emergency Cash in Small Denominations',
    },
    description: {
      ceb: 'Dili mugana ang ATM o GCash kun walang kuryente o signal.',
      fil: 'Hindi gagana ang electronic payment kapag walang kuryente.',
      en: 'ATMs and online transfers will be offline during power cuts.',
    },
    checked: false,
    isEssential: true,
  },
  {
    id: 'gb-hygiene',
    category: 'sanitation',
    title: {
      ceb: 'Hygiene Kit (Sabon, Toothbrush, Alcohol, Sanitary Napkin, Tissue)',
      fil: 'Hygiene Kit (Sabon, Toothbrush, Tisyu)',
      en: 'Hygiene Kit (Soap, Toothbrush, Wet Wipes, Hand Sanitizer, Sanitary Pads)',
    },
    description: {
      ceb: 'Alang sa kalimpyo ug paglikay sa sakit sa evacuation center.',
      fil: 'Para sa kalinisan.',
      en: 'Prevents spread of waterborne and communicable illness in evacuation centers.',
    },
    checked: false,
    isEssential: true,
  },
  {
    id: 'gb-clothes',
    category: 'sanitation',
    title: {
      ceb: 'Mao nga Sapot, Raincoat, ug Plastic Sheet / Blanket',
      fil: 'Ekstrang damit, kapote, at kumot',
      en: 'Extra Change of Clothes, Raincoat & Warm Blanket',
    },
    description: {
      ceb: 'Importante nga dili mabasa ug matugnawan.',
      fil: 'Mapanatiling tuyo at mainit ang katawan.',
      en: 'Keeps household members dry and warm during stormy weather.',
    },
    checked: false,
    isEssential: false,
  },
];

export const OFFICIAL_SOURCES = [
  {
    name: 'ICDRRMD Official Facebook Page',
    url: 'https://www.facebook.com/drrmoiligancity',
    description: 'Official 24/7 disaster advisories, river water level monitoring, and emergency rescue notices from Iligan City DRRMD.',
    tag: 'ICDRRMD_FB',
  },
  {
    name: 'Iligan City Official Government Portal',
    url: 'https://iligan.gov.ph/',
    description: 'Official announcements, ordinances, and executive orders of Iligan City.',
    tag: 'ILIGAN_LGU',
  },
  {
    name: 'DOST-PAGASA (Weather & Tropical Cyclones)',
    url: 'https://www.pagasa.dost.gov.ph/',
    description: 'National weather forecasts, typhoon signals, and heavy rainfall advisories.',
    tag: 'PAGASA',
  },
  {
    name: 'DOST-PHIVOLCS (Earthquake & Tsunami)',
    url: 'https://www.phivolcs.dost.gov.ph/',
    description: 'Official earthquake bulletins, tsunami warnings, and volcano monitoring.',
    tag: 'PHIVOLCS',
  },
  {
    name: 'NDRRMC (National Disaster Risk Reduction & Management)',
    url: 'https://ndrrmc.gov.ph/',
    description: 'National situational reports and disaster management directives.',
    tag: 'NDRRMC',
  },
];

export const SAMPLE_ADVISORIES: AdvisoryItem[] = [
  {
    id: 'adv-1',
    title: 'ICDRRMD Weather Alert: Localized Thunderstorms over Lanao del Norte',
    agency: 'PAGASA',
    type: 'weather',
    level: 'advisory',
    content: 'DOST-PAGASA issues Thunderstorm Advisory. Expect moderate to heavy rainfall with lightning and strong winds over Iligan City within the next 1-2 hours. Low-lying areas near riverbanks are advised to monitor water levels.',
    date: '2026-08-13 09:30 AM',
    link: 'https://www.pagasa.dost.gov.ph/',
  },
  {
    id: 'adv-2',
    title: 'PHIVOLCS Bulletin: Regional Seismic Status Monitoring',
    agency: 'PHIVOLCS',
    type: 'earthquake',
    level: 'info',
    content: 'DOST-PHIVOLCS reports normal background seismic monitoring in Northern Mindanao. No active tsunami threats for Iligan Bay coastal zones.',
    date: '2026-08-13 08:00 AM',
    link: 'https://www.phivolcs.dost.gov.ph/',
  },
  {
    id: 'adv-3',
    title: 'Iligan ICDRRMD Reminder: Family Emergency Preparedness & 24/7 Hotlines',
    agency: 'ILIGAN_ICDRRMD',
    type: 'general',
    level: 'info',
    content: 'All 44 barangays of Iligan City are encouraged to review their local evacuation plans and inspect household Go-Bags. For 24/7 emergency response, contact ICDRRMD Communication Center: (063) 221-8459, 0997-726-2692 (Globe), 0969-233-7878 (Smart). Official updates at facebook.com/drrmoiligancity.',
    date: '2026-08-13 02:00 PM',
    link: 'https://www.facebook.com/drrmoiligancity',
  },
];
